### PR TITLE
coding style after manual pass, should look good enough

### PR DESCRIPTION
**Pull request by v01d**
@btashton @adamfeuer 
Please have a look at the coding style (maybe you should try to checkout the `coding_style` yourself and build locally to see how it looks).
I've manually added all code examples (ugh), and fixed many things that pandoc missed. Since this document is a bit sensitive it would be cool to have a look and compare to original Coding Style HTML side-by-side. There's at least one case where sphinx does not respect the indentation (marked with a note). Also, I use note/error/etc for correct/incorrect code samples but to make that work I had to find just the right indentation for RST markup, otherwise it would not render correctly. For some reason as it is now, it triggers a lot of indentation warnings. I'm not sure if I'm doing it wrong.
Maybe for this we should use some custom RST directive which does not have this problem (or maybe there's a better way with pure RST). 
Finally, I added section numbering since it helps when reading such a large document (as it was in the original HTML), but the main section is numbered with "1" which should be fixed (can't find how). Anyway, this is now very close to something I'd feel comfortable sharing in the mailing list for other to see.

### CODE REVIEW

**Comment by adamfeuer** [comment]
@v01d I will check it out and build locally.

**Comment by adamfeuer** [comment]
@v01d I like the Error, Hint, and Note boxes for unacceptable, preferred, and acceptable. They look cool with the nice colors.

The indentation can be fixed this way:

```
.. error:: This is incorrect  

   .. code-block:: c

       struct some_long_struct_name_s
       {
         struct some_long_struct_name_s *flink;  /* The forward link to the next instance of struct some_long_struct_name_s in a singly linked list */
         int short_name1;   /* Short comment 1 */
         int short_name2;   /* This is a very long comment describing subtle aspects of the short_name2 field */
       };
```

Any valid pygments style will work, 'c', 'bash', etc.; or 'text' for unhighlighted code. 

You can also do it your way with similar indentation like this:

```
.. error:: This is incorrect  

   ::

       struct some_long_struct_name_s
       {
         struct some_long_struct_name_s *flink;  /* The forward link to the next instance of struct some_long_struct_name_s in a singly linked list */
         int short_name1;   /* Short comment 1 */
         int short_name2;   /* This is a very long comment describing subtle aspects of the short_name2 field */
       };
```

I think you were just missing a blank line and the indentation wasn't right.

**Comment by v01d** [comment]
> @v01d I like the Error, Hint, and Note boxes for unacceptable, preferred, and acceptable. They look cool with the nice colors.

Yeah, the colors look nice. I don't like all the extra space and also would like them to be simply "incorrect" and not "Error" with a first line that says "This is incorrect" which needs to be added manually every time. Anyway, it is minor and can be improved later.

> 
> The indentation can be fixed this way:
> 
> ```
> .. error:: This is incorrect  
> 
>    .. code-block:: c
> 
>        struct some_long_struct_name_s
>        {
>          struct some_long_struct_name_s *flink;  /* The forward link to the next instance of struct some_long_struct_name_s in a singly linked list */
>          int short_name1;   /* Short comment 1 */
>          int short_name2;   /* This is a very long comment describing subtle aspects of the short_name2 field */
>        };
> ```
> 
> Any valid pygments style will work, 'c', 'bash', etc.; or 'text' for unhighlighted code.

I'm still learning RST and I'm a bit confused on all the different ways to do the same thing. What is the difference between "code-block:: c" and "::" (where sphinx defaults to C)? If both are the same I would rather use the shorter one.

> 
> You can also do it your way with similar indentation like this:
> 
> ```
> .. error:: This is incorrect  
> 
>    ::
> 
>        struct some_long_struct_name_s
>        {
>          struct some_long_struct_name_s *flink;  /* The forward link to the next instance of struct some_long_struct_name_s in a singly linked list */
>          int short_name1;   /* Short comment 1 */
>          int short_name2;   /* This is a very long comment describing subtle aspects of the short_name2 field */
>        };
> ```
> 
> I think you were just missing a blank line and the indentation wasn't right.
> 
> (I fetched your coded and tested that both of these work.)

Spacing requirements and indentation are really fiddly sometimes. I couldn't find a very good specification either on how to use it properly, specially when some directives are sphinx-specific and others generic.

I'll change these to avoid the warnings and push again.

**Comment by adamfeuer** [comment]
> I'm still learning RST and I'm a bit confused on all the different ways to do the same thing. What is the difference between "code-block:: c" and "::" (where sphinx defaults to C)? If both are the same I would rather use the shorter one.

I am also a RST and Sphinx newbie. But I think `::` is a preformatted text directive, for any kind of preformatted text, and doesn't do highlighting:

https://www.sphinx-doc.org/en/master/usage/restructuredtext/basics.html#literal-blocks

While the `..code-block: c` will actually use pygments to highlight the code block:

https://www.sphinx-doc.org/en/master/usage/restructuredtext/directives.html#directive-code-block

Both need correct indentation and blank lines before the directive, after the directive, and after the indented code block...

> 
> > You can also do it your way with similar indentation like this:
> > ```
> > .. error:: This is incorrect  
> > 
> >    ::
> > 
> >        struct some_long_struct_name_s
> >        {
> >          struct some_long_struct_name_s *flink;  /* The forward link to the next instance of struct some_long_struct_name_s in a singly linked list */
> >          int short_name1;   /* Short comment 1 */
> >          int short_name2;   /* This is a very long comment describing subtle aspects of the short_name2 field */
> >        };
> > ```
> > 
> > 
> > I think you were just missing a blank line and the indentation wasn't right.
> > (I fetched your coded and tested that both of these work.)
> 
> Spacing requirements and indentation are really fiddly sometimes. I couldn't find a very good specification either on how to use it properly, specially when some directives are sphinx-specific and others generic.
> 
> I'll change these to avoid the warnings and push again.

**Comment by v01d** [comment]
Ah, maybe they use different engines for highlighting. I can see "struct" and "int" keywords being colored with "::". I will check how it looks with the other directive.

**Comment by adamfeuer** [comment]
@v01d I see that the `conf.py` defaults all preformatted blocks to `c` highlighting. So that's where the c-style highlighting is coming from. I think we should eventually turn that off, so that we can use the `::` for regular preformatted text, and use `..code-block:` for other languages... it's ok for now though.

**Comment by v01d** [comment]
Ok, I will switch that off and change these to code-block.

**Pull request merged**
