### PR TITLE
Add github ci hook for building Sphinx documentation

### PR DESCRIPTION
**Pull request by btashton**
# Summary
Add github ci hook for building Sphinx documentation.  This will also create a build artifact containing the generated HTML docs.

### CODE REVIEW

**Comment by btashton** [comment]
There is a run here with only the doc CI running https://github.com/btashton/incubator-nuttx/actions/runs/176487921

**Comment by v01d** [comment]
Great! 
Is there a way not run code-related jobs on changesets which only affect doc/? That would probably save a lot of time not having to wait for really long builds with documentation PRs.

**Comment by btashton** [comment]
I normally just remove the other workflow yaml files if I need to iterate. One you could remove that on this branch and then when it's ready to merge in rebase the whole thing and remove that commit.

**Comment by v01d** [comment]
I imagine that in order to have different documentation versions selectable in the final html (like zephyr does here: docs.zephyrproject.org/) there would need to be a publish job for each tag right (besides for master)?

**Comment by btashton** [comment]
> I imagine that in order to have different documentation versions selectable in the final html (like zephyr does here: docs.zephyrproject.org/) there would need to be a publish job for each tag right (besides for master)?  

My thought on this is to have a CI job in the website that would check out the version and add them to the content it publishes. We might have to do something a little fancy with the token to trigger it, but I'm sure we can work it out.

**Comment by v01d** [comment]
> I normally just remove the other workflow yaml files if I need to iterate. You could remove them on this branch and then when it's ready to merge in to master rebase the whole thing and remove that commit.

Actually I just found this: https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#onpushpull_requestpaths
It seems very simple, just add a on: `push: paths: - doc/**`. Or negate it for the code CI jobs.

**Comment by btashton** [comment]
> > I normally just remove the other workflow yaml files if I need to iterate. You could remove them on this branch and then when it's ready to merge in to master rebase the whole thing and remove that commit.
> 
> Actually I just found this: https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#onpushpull_requestpaths
> It seems very simple, just add a on: `push: paths: - doc/**`. Or negate it for the code CI jobs.

Ah cool. Yeah we could do that. Probably will still trigger the first time because of the change to the workflow file which is outside of doc/

**Comment by btashton** [comment]
Ok.  I made that change and it looks like at least for this PR it will run all of the jobs.  I did not restrict the doc building since I suspect we might pull in the readme files outside of the docs directory (and it is fast).

**Comment by v01d** [comment]
Great, I will merge this then so that following PRs use this new change and only run the doc job.
I was about to setup readthedocs integration to preview the result prior to your PR, but I think it is best to use GitHub pages for that now that you added this job. I can look into that tomorrow.

**Comment by btashton** [comment]
If you want to publish the built content to a branch (I think that is how it works), check out what I did over here for the website
https://github.com/apache/incubator-nuttx-website/blob/master/.github/workflows/main.yml
and
https://github.com/apache/incubator-nuttx-website/blob/master/publish.sh

Note we cannot use github pages in the actual project but for demo this could be good.

**Comment by v01d** [comment]
I'm trying to figure out how it would once integrated on the final repo. I like how zephyr offers links to different versions of the docs. It seems they simply generate the docs for each version and publish to a subdirectory of their webserver.

The NuttX website repo uses GitHub pages right? In that case to get something similar we would have to create one branch per version of the docs, which sounds messy. I don't even know if GitHub pages allow you to publish different versions.

I we want to have the docs regenerated in doc PRs and on each doc commit to NuttX master, how would the website repo get this result? Is it possible to trigger the CI job of another repo?

Maybe we can ask Apache to allow publishing to the pages of the NuttX repo to build the docs there and have the website link to it.

Just thinking out loud...

**Comment by btashton** [comment]
> I'm trying to figure out how it would work once integrated on the final repo. I like how zephyr offers links to different versions of the docs. It seems they simply generate the docs for each version and publish to a subdirectory of their webserver.

Yep which we can easily do here as well.
> 
> The NuttX website repo uses GitHub pages right? In that case to get something similar we would have to create one branch per version of the docs, which sounds messy. I don't even know if GitHub pages allow you to publish different versions.

No it uses some custom Apache infrastructure.  But if effectively works the same way there is a special branch that only contains the final HTML. 

> 
> I we want to have the docs regenerated in doc PRs and on each doc commit to NuttX master, how would the website repo get this result? Is it possible to trigger the CI job of another repo?
> 
> Maybe we can ask Apache to allow publishing to the pages of the NuttX repo to build the docs there and have the website link to it.
> 
> Just thinking out loud...
> 

So what I think we do is that we have the CI in the OS repo do the build test kind of like what we have here. But does not actually do the publishing. 

The merge triggers the website CI which would check out a copy of all the versions of interest, build them and publish them alongside the existing website content.

**Comment by v01d** [comment]
> So what I think we do is that we have the CI in the OS repo do the build test kind of like what we have here. But does not actually do the publishing.
> 
> The merge triggers the website CI which would check out a copy of all the versions of interest, build them and publish them alongside the existing website content.

If that's possible, perfect. For now I will enable gh-pages here and will see if I manage to make it publish each version in a subdirectory.

**Pull request merged**
